server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/trafficshield}
    username: ${SPRING_DATASOURCE_USERNAME:trafficshield}
    password: ${SPRING_DATASOURCE_PASSWORD:trafficshield}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

trafficshield:
  appBaseUrl: ${APP_BASE_URL:http://localhost:8080}
  services:
    user-service:
      loadBalancingStrategy: ROUND_ROBIN
      rateLimit:
        capacity: 5
        refillRatePerSecond: 1
      circuitBreaker:
        failureThreshold: 3
        openDurationSeconds: 30
      instances:
        - instanceId: user-service-1
          baseUrl: ${trafficshield.appBaseUrl}/mock/user-service-1
          weight: 1
        - instanceId: user-service-2
          baseUrl: ${trafficshield.appBaseUrl}/mock/user-service-2
          weight: 1

    payment-service:
      loadBalancingStrategy: WEIGHTED_ROUND_ROBIN
      rateLimit:
        capacity: 10
        refillRatePerSecond: 2
      circuitBreaker:
        failureThreshold: 3
        openDurationSeconds: 30
      instances:
        - instanceId: payment-service-1
          baseUrl: ${trafficshield.appBaseUrl}/mock/payment-service-1
          weight: 3
        - instanceId: payment-service-2
          baseUrl: ${trafficshield.appBaseUrl}/mock/payment-service-2
          weight: 1