CREATE TABLE IF NOT EXISTS request_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(100) NOT NULL,
    service_name VARCHAR(100) NOT NULL,
    selected_instance VARCHAR(100) NOT NULL,
    target_url CLOB NOT NULL,
    status_code INT NOT NULL,
    success BOOLEAN NOT NULL,
    outcome_type VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN',
    latency_ms BIGINT NOT NULL,
    error_message CLOB,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_request_metrics_service_name
ON request_metrics(service_name);

CREATE INDEX IF NOT EXISTS idx_request_metrics_created_at
ON request_metrics(created_at);

CREATE INDEX IF NOT EXISTS idx_request_metrics_success
ON request_metrics(success);

CREATE INDEX IF NOT EXISTS idx_request_metrics_outcome_type
ON request_metrics(outcome_type);